spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apptive
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true